### ISSUE TITLE
wrn_kaggle.ipynb

### ISSUE THREAD

**Issue by Angzz** [SinyerAtlantis/deep_learning_gluon#1]
你好，你的output中给的是train_acc。。。 我说怎么长的这么快
另外，这个模型过拟合很严重，从前几轮就有明显的症状了，
我很是怀疑这个wrn会不会有很好的valid_acc啊。。。

**Comment by SinyerAtlantis** [comment]
你可以看看前面用cifar10官方数据集训练的代码，里面贴出了每轮官方测试集的准确率变化，kaggle最终评测和官方测试是基本一致的

**Comment by Angzz** [comment]
好的 多谢
